#!/bin/bash

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
:
# <<< conda initialize <<<
# Fix error related to the conda usage
export -f conda
export -f __conda_exe
export -f __conda_activate
export -f __conda_reactivate
export -f __conda_hashr
