#!/bin/bash


######### BASH HISTORY #########
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
# ensures that the command history remains up-to-date across different terminal sessions.
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
# ignore duplicate commands
export HISTSIZE=9999
export HISTFILESIZE=999999
export HISTFILE="$HOME/.history"
export HISTTIMEFORMAT="[%F %T] "


######### TERMINAL SIZE #########
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
