# Define an array of symbolic link sources and targets
$(pwd)/bash/.bashrc:$HOME/.bashrc
$(pwd)/bash/aliases.bash:$HOME/.config/bash/aliases.bash
$(pwd)/bash/custom.bash:$HOME/.config/bash/custom.bash
$(pwd)/bash/git-completion.bash:$HOME/.config/bash/git-completion.bash
$(pwd)/bash/git-prompt.sh:$HOME/.config/bash/git-prompt.sh
$(pwd)/bash/miniforge3.bash:$HOME/.config/bash/miniforge3.bash
$(pwd)/bash/yabpc.bash:$HOME/.config/bash/yabpc.bash
$(pwd)/helix:$HOME/.config/helix
$(pwd)/wezterm:$HOME/.config/wezterm
